[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.cursor]
cursor = "#67ff4f"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
bright_foreground = "#f28779"
foreground = "#CBCCC6"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

#[cursor]
#blinking_interval = 500

[cursor.style]
blinking = "Always"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "CaskaydiaMono NFP"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "CaskaydiaMono NF Light"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

#[window]
#dinamic_padding = false

[window.padding]
x = 2
y = 2
