#!/usr/bin/env bash
set -e

SSH_DIR="$HOME/.ssh"
DOTFILES="$HOME/dotfiles"
REPOS="$HOME/Desktop/repos"

#check for ansible
if ! [ -x "$(command -v ansible)" ]; then
	sudo pacman -S ansible --noconfirm
fi

#check for dotfiles repository
if ! [[ -d $DOTFILES ]]; then
	git clone https://github.com/sirArthurDayne/dotfiles "$DOTFILES"
else
	git -C "$DOTFILES" pull
fi

if ! [[ -d $SSH_DIR ]]; then
	mkdir -p $SSH_DIR
fi

if [[ -f "$DOTFILES/requirements.yml" ]]; then
	cd "$DOTFILES"
	ansible-galaxy install -r requirements.yml
fi

cd "$DOTFILES"

if [[ -f "$DOTFILES/vault-password.txt" ]];  then
	ansible-playbook --diff --vault-password-file "$DOTFILES/vault-password.txt" "$DOTFILES/main.yml"
else
	ansible-playbook --diff "$DOTFILES/main.yml"
fi
