#!/usr/bin/env bash
set -e
# check for ansible
if ! [ -x "$(command -v ansible)" ]; then
	sudo pacman -S ansible --noconfirm
fi

if [[ -f "requirements.yml" ]]; then
	ansible-galaxy install -r requirements.yml
fi

if [[ -f "vault-password.txt" ]];  then
	ansible-playbook --diff --vault-password-file "./vault-password.txt" "./main.yml"
else
	ansible-playbook --diff --ask-vault-pass "./main.yml"
fi
