---
- name: Playbook Arch Setup
  hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache before running tasks...
      pacman:
        update_cache: true
      tags:
        - zsh
        - node
  tasks:
    - name: Install ZSH
      tags:
        - zsh
      pacman:
        name: zsh
    - name: Change shell to ZSH
      shell: chsh -s `which zsh`
      tags:
        - zsh
    - name: Install nodejs and npm
      tags:
      - node
      pacman:
        name: [ "nodejs", "npm" ]
        update_cache: true
        upgrade: true
    - name: Install n (for nvm)
      tags:
      - node
      npm:
        name: n
        global: true
    - name: Symlinks my dotfiles
      tags:
      - dotfiles
      script: ./install.sh
