---
- name: Playbook Arch Setup
  hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  become: true
  pre_tasks:
    - name: Update cache before running tasks...
      pacman:
        update_cache: true
        upgrade: true
      tags:
        - install
        - core
  tasks:
    # - include: tasks/aur-setup.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/dotfiles-setup.yml
