---
- name: make directories for paru
  file:
    path: "{{ lookup('env', 'HOME') }}/repos"
    state: directory
    mode: 0777
- name: download paru (AUR-helper)
  tags:
    - install
    - core
  ansible.builtin.git:
    repo: 'https://aur.archlinux.org/paru-bin.git'
    dest: "{{ lookup('env', 'HOME') }}/repos/paru-bin"
- name: install paru
  tags:
    - install
    - core
  shell: "cd {{ lookup('env', 'HOME') }}/repos/paru-bin && makepkg -si"
