- name: Install ZSH
  become: true
  tags:
  - zsh
  pacman:
    name: zsh
- name: Change shell to ZSH
  shell: chsh -s $(which zsh)
  tags:
  - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.git:
  repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
  dest: "~/Desktop/repos/zsh-autosuggestions"
  tags:
    - zsh
