- name: Install ZSH
  become: true
  tags:
    - zsh
    - install
  pacman:
    name: zsh
- name: Change shell to ZSH
  shell: chsh -s $(which zsh)
  tags:
    - zsh
    - install
- name: Install zsh-autosuggestions
  ansible.builtin.git:
  repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
  dest: "{{ lookup('env', 'HOME') }}/repos/zsh-autosuggestions"
  tags:
    - zsh
    - install
