local remap = require("krosis.keymaps")
local nnoremap = remap.nnoremap
local dapui = require("dapui")
local dap = require("dap")

nnoremap("<Home>", function()
    dapui.toggle(1)
end)
nnoremap("<End>", function()
    dapui.toggle(2)
end)

nnoremap("<leader>dq", function()
    dap.close()
end)

nnoremap("<F5>", function()
    dap.continue()
end)
nnoremap("<Right>", function()
    dap.step_over()
end)
nnoremap("<Down>", function()
    dap.step_into()
end)
nnoremap("<Up>", function()
    dap.step_out()
end)
nnoremap("<Leader>db", function()
    dap.toggle_breakpoint()
end)
nnoremap("<Leader>dB", function()
    dap.set_breakpoint(vim.fn.input('Breakpoint condition: '))
end)
nnoremap("<leader>rc", function()
    dap.run_to_cursor()
end)

-- nnoremap("<Leader>dr", function()
--     dap.repl.open()
-- end)
--
-- nnoremap("<Leader>dl", function()
--     dap.run_last()
-- end)
--
-- nnoremap("<Leader>dbp", function()
--     dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))
-- end)
